# Generated by Django 3.1 on 2020-10-11 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=40)),
                ('startingyear', models.IntegerField()),
                ('endingyear', models.IntegerField()),
                ('grade', models.CharField(max_length=4)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('startingyear', models.IntegerField()),
                ('endingyear', models.IntegerField()),
                ('post', models.CharField(max_length=20)),
                ('details', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=40)),
                ('startingyear', models.IntegerField()),
                ('endingyear', models.IntegerField()),
                ('details', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='xyz', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='emailid',
            field=models.EmailField(default='m@g', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phoneno',
            field=models.IntegerField(default=971),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='pincode',
            field=models.IntegerField(default=971),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(default='stu', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='profile',
            field=models.TextField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(default='ef', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(default='wer', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='whole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addcv.education')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addcv.experience')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addcv.person')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addcv.projects')),
            ],
        ),
    ]
