# Generated by Django 3.1 on 2020-10-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0002_auto_20201011_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ManyToManyField(to='addcv.education')),
                ('experience', models.ManyToManyField(to='addcv.experience')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addcv.person')),
                ('project', models.ManyToManyField(to='addcv.projects')),
            ],
        ),
        migrations.DeleteModel(
            name='whole',
        ),
    ]
