# Generated by Django 3.0.6 on 2020-10-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0003_auto_20201019_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addcv.person'),
        ),
    ]
