# Generated by Django 3.1 on 2020-10-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0003_auto_20201014_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resumename',
            field=models.CharField(default='part1', max_length=40),
            preserve_default=False,
        ),
    ]
