# Generated by Django 3.0.6 on 2020-10-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0004_auto_20201021_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addcv.person'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addcv.person'),
        ),
    ]
