# Generated by Django 3.0.6 on 2020-10-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0005_auto_20201021_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(blank=True, max_length=40)),
                ('skill2', models.CharField(blank=True, max_length=40)),
                ('skill3', models.CharField(blank=True, max_length=40)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addcv.person')),
            ],
        ),
    ]
