# Generated by Django 3.1 on 2020-10-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0006_auto_20201017_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
    ]
