# Generated by Django 3.0.6 on 2020-10-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0006_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tempid',
            field=models.IntegerField(null=True),
        ),
    ]
