# Generated by Django 3.0.6 on 2020-10-30 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0008_auto_20201029_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tempid',
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.CharField(blank=True, max_length=40)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addcv.person')),
            ],
        ),
    ]
