# Generated by Django 3.1 on 2020-10-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0013_person_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='endingyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='startingyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='details',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='endingyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='post',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startingyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='endingyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='startingyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='topic',
            field=models.CharField(max_length=80),
        ),
    ]
